# Generated by Django 3.2.1 on 2024-12-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigManger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='name',
            field=models.CharField(default=0, max_length=255, unique=True, verbose_name='解析通道名'),
        ),
    ]
